MusicPro/urls.py
from django.contrib import admin
from django.forms.widgets import Media
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('', include('pwa.urls'))
]

admin.site.site_title ="Planta Corp"
admin.site.site_header ="Administracion Planta Corp"
admin.site.index_title = "Modulos de la aplicacion"



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path,include
from .views import *
from rest_framework import routers


router = routers.DefaultRouter()
router.register('producto',ProductoViewset)
router.register('cliente',ClienteViewset)
router.register('descuento',DescuentoViewset)
router.register('suscripcion',SuscripcionViewset)


urlpatterns = [
    path('', index, name="index"),
    path('productos/', productos, name="productos"),
    path('contacto/', contacto, name="contacto"),
    path('pago/', pago, name="pago"),
    path('login/', login, name="login"),
    path('agregar_producto/', agregar_producto, name="agregar_producto"),
    path('modificar_producto/<id>/', modificar_producto, name="modificar_producto"),
    path('eliminar_producto/<id>/', eliminar_producto, name="eliminar_producto"),
    path('modificar/', modificar, name="modificar"),
    path('signup/', signup, name="signup"),
    path('api/',include(router.urls)),
    path('donaciones/', donaciones, name="donaciones"),
    path('suscripcion/', suscripcion, name="suscripcion"),
    path('descuentos/', descuentos, name="descuentos"),
]

app/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Categoria(models.Model):
    categoria = models.CharField(max_length=40)
    def __str__(self):
        return self.categoria

class Producto(models.Model):
    codigo = models.CharField(max_length=40)
    nombre = models.CharField(max_length=40)
    precio = models.IntegerField()
    stock = models.IntegerField()
    descripcion = models.CharField(max_length=40)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha = models.DateField()
    imagen = models.ImageField(null=True, blank=True)



    def __str__(self):
        return self.nombre

class Cliente(models.Model):
    nombre = models.CharField(max_length=41)
    paterno = models.CharField(max_length=40)
    rut = models.CharField(max_length=9)
    direccion = models.CharField(max_length=40)
    telefono = models.IntegerField()
    mail = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

class Usuario(models.Model):
    mail = models.CharField(max_length=100)
    contraseña = models.CharField(max_length=100)
    rut = models.ForeignKey(Cliente, on_delete=models.CASCADE)

    def __str__(self):
        return self.rut

class DetalleVenta(models.Model):
    tipo_comprovante = models.CharField(max_length=100)
    serie_comprovante = models.CharField(max_length=7)
    fecha_comprovante = models.DateField(max_length=100)
    iva = models.IntegerField()
    total = models.IntegerField()

    def __str__(self):
        return self.serie_comprovante
    
class Descuento(models.Model):
    codigo_descuento = models.CharField(max_length=7)
    valor_descuento = models.IntegerField()

    def __str__(self):
        return self.codigo_descuento

class Venta(models.Model):
    descripcion = models.CharField(max_length=100)
    total_venta = models.IntegerField()

    def __str__(self):
        return self.total_venta

class Sucursal(models.Model):
    direccion = models.CharField(max_length=100)
    numero_sucursal = models.IntegerField()

    def __str__(self):
        return self.numero_sucursal

class Comuna(models.Model):
    direccion = models.CharField(max_length=100)
    numero_comuna = models.IntegerField()
    numero_sucursal = models.ForeignKey(Sucursal, on_delete=models.DO_NOTHING)
    
    def __ (self):
        return self.numero_sucursal

class Region(models.Model):
    direccion = models.CharField(max_length=100)
    numero_region = models.IntegerField()
    numero_comuna= models.ForeignKey(Comuna,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.numero_region

class Pedido(models.Model):
    numero_pedido = models.IntegerField()
    fecha_pedido = models.DateField(max_length=100)
    iva = models.IntegerField()

    def __int__(self):
        return self.numero_pedido


class Proveedores(models.Model):
    nombre_proveedor = models.CharField(max_length=40)
    direccion = models.CharField(max_length=40)
    telefono = models.IntegerField()
    mail = models.CharField(max_length=100)
    numero_pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING)
    
    def __str__(self):
        return self.nombre_proveedor

class Suscripcion(models.Model):
    fecha_suscripcion = models.DateField
    valor_suscripcion = models.IntegerField()
    suscrito = models.IntegerField()

app/templates/app/agregar_producto.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}

<link rel="stylesheet" href="{% static 'app/dist/css/agremod.css' %}">
<body>
    <section class="forma">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <div>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table>
                            {{form|crispy}}
                        </table>
                        {% if perms.app.add_producto %}
                        <input type="submit" class="btn btn-success" value="Guardar">
                        <input type="reset" class="btn btn-danger" value="Limpiar">
                        {% endif %}
                    </form>
                </div>
                {{mensaje}}
            </div>
            <div class="col-sm-2"></div>
        </div>
    </section>
</body>

{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>
    {% load static %}
    {% block css %}

    {% endblock %}
    {% load pwa %}
    
    {% progressive_web_app_meta %}
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'app/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{% static 'app/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'app/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'app/plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'app/dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'app/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{% static 'app/plugins/daterangepicker/daterangepicker.css' %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{% static 'app/plugins/summernote/summernote-bs4.min.css' %}">


</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->


        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'index' %}" class="nav-link">Inicio</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'suscripcion' %}" class="nav-link">suscribirse</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'logout' %}" class="nav-link">cerrar sesión</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="#" class="nav-link"> {{ user.username }} </a>
                </li>
                {% else %}
                <li class="nav-item d-none d-sm-inline-block">
                    <a href="{% url 'login' %}" class="nav-link">iniciar sesión</a>
                </li>
                {% endif %}

            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>

            </ul>
        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->

        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="{% url 'index' %}" class="brand-link">
                <img src="{% static 'app/dist/img/LogoPlanta.png' %}" alt="AdminLTE Logo"
                    class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Special Garden</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                        <li class="nav-header">Nosotros</li>
                        <li class="nav-item">
                            <a href="{% url 'productos' %}" class="nav-link">
                                <i class="nav-icon fa fa-inbox"></i>
                                <p>Productos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'contacto' %}" class="nav-link">
                                <i class="nav-icon far fa-user"></i>
                                <p>Contacto</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'pago' %}" class="nav-link">
                                <i class="nav-icon fa fa-users"></i>
                                <p>Pago</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'donaciones' %}" class="nav-link">
                                <i class="nav-icon fa fa-users"></i>
                                <p>Donaciones</p>
                            </a>
                        </li>
                        {% if perms.app.add_producto %}
                        <li class="nav-item">
                            <a href="{% url 'agregar_producto' %}" class="nav-link">
                                <i class="nav-icon fa fa-inbox"></i>
                                <p>Agregar Productos</p>
                            </a>
                        </li>
                        {% endif %}

                        {% if perms.app.add_descuentos %}
                        <li class="nav-item">
                            <a href="{% url 'descuentos' %}" class="nav-link">
                                <i class="nav-icon fa fa-inbox"></i>
                                <p>Agregar descuento</p>
                            </a>
                        </li>
                        {% endif %}

                        {% if perms.app.change_producto %}
                        <li class="nav-item">
                            <a href="{% url 'modificar' %}" class="nav-link">
                                <i class="nav-icon fa fa-inbox"></i>
                                <p>Modificar Producto</p>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">
                            {% block contenido %}

                            {% endblock %}
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.1.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="{% static 'app/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'app/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'app/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->
    <script src="{% static 'app/plugins/chart.js/Chart.min.js' %}"></script>
    <!-- Sparkline -->
    <script src="{% static 'app/plugins/sparklines/sparkline.js' %}"></script>
    <!-- JQVMap -->
    <script src="{% static 'app/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
    <script src="{% static 'app/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{% static 'app/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
    <!-- daterangepicker -->
    <script src="{% static 'app/plugins/moment/moment.min.js' %}"></script>
    <script src="{% static 'app/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{% static 'app/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <!-- Summernote -->
    <script src="{% static 'app/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{% static 'app/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'app/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'app/dist/js/demo.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'app/dist/js/pages/dashboard.js' %}"></script>
    {% block javascript %}

    {% endblock %}
</body>

</html>

app/templates/app/contacto.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'app/dist/css/agremod.css' %}">
<section class="forma">
    <div class="row">
        <div class="col-lg-1 col-1">
            <div class="small-box bg-info">
            </div>
        </div>
        <div class="col-lg-10 col-12">
            <div>
                <div class=" text-center">
                    <h1 class="display-4 mt-4">Nuestros Contactos</h1>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col l6 s12">
                            <h2 class="white-text">Huerto especial</h2>
                            <h6 class="white-text text-lighten-6">PLANTA TUS SUEÑOS Y CRECERÁN DÍAS FELICES
                            </h6>
                            <h6>
                                ENCUENTRANOS EN ESTA DIRECCIÓN:
                            </h6>

                            <iframe
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3323.265734954597!2d-70.58078458479675!3d-33.598408990056875!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662d7037854df81%3A0x893f58a1479b8f82!2sDuoc%20UC%3A%20Sede%20Puente%20Alto!5e0!3m2!1ses!2scl!4v1618666456134!5m2!1ses!2scl"
                                width="400" height="250" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

                        </div>
                        <div class="col l4 offset-l2 s12">
                            <h2 class="white-text">Siguenos en nuestras redes Sociales:</h2>
                            <ul>
                                <a href="https://www.facebook.com/"><img
                                        src="{% static 'app/dist/img/IconFacebook.png' %}" alt="" width="54"
                                        height="55"></a>
                                <a href="https://www.instagram.com/"><img
                                        src="{% static 'app/dist/img/IconInstagram.png' %}" alt="" width="54"
                                        height="55"></a>
                                <a href="https://twitter.com/?lang=es"><img
                                        src="{% static 'app/dist/img/IconTiwtter.png' %}" alt="" width="54"
                                        height="55"></a>
                                <a href="https://web.whatsapp.com/"><img
                                        src="{% static 'app/dist/img/IconWhatsapp.png' %}" alt="" width="54"
                                        height="55"></a>
                                <div>
                                    <p class="LetrasFooter">Contacto Legal: Planta.viva@gmail.com</p>
                                    <p class="LetrasFooter">Encuentranos en: Duoc, Sede Puente Alto</p>
                                    <p class="LetrasFooter">Llamanos al Fono: (+56) 2 2999 3862</p>
                                    <p><img src="{% static 'app/dist/img/LogoPlanta.png' %}" alt="" height="150px"
                                            width="150px"></p>

                                </div>
                            </ul>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-lg-1 col-1">
                <div class="small-box bg-danger">
                </div>
            </div>
        </div>
</section>
{% endblock %}

app/templates/app/descuentos.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}

<link rel="stylesheet" href="{% static 'app/dist/css/agremod.css' %}">
<body>
    <section class="forma">
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <div>
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table>
                            {{form|crispy}}
                        </table>
                        {% if perms.app.add_descuentos %}
                        <input type="submit" class="btn btn-success" value="Guardar">
                        <input type="reset" class="btn btn-danger" value="Limpiar">
                        {% endif %}
                    </form>
                </div>
                {{mensaje}}
            </div>
            <div class="col-sm-2"></div>
        </div>
    </section>
</body>

{% endblock %}

app/templates/app/donaciones.html
{% extends 'app/base.html' %}
{% load static %}


{% block contenido %}

<div class='credit-info'>
    <div class='credit-info-content'>
        <table class='half-input-table'>
            <tr>
                <td>Por favor seleccione su tarjeta: </td>
                <td>
                    <div class='dropdown' id='card-dropdown'>
                        <div class='dropdown-btn' id='current-card'>Visa</div>
                        <div class='dropdown-select'>
                            <ul>
                                <li>Master Card</li>
                                <li>American Express</li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        </table>
        <img src='https://dl.dropboxusercontent.com/s/ubamyu6mzov5c80/visa_logo%20%281%29.png' height='80'
            class='credit-card-image' id='credit-card-image'></img>
        Número de tarjeta
        <input class='input-field'></input>
        Titular de la tarjeta
        <input class='input-field'></input>
        
        <table class='half-input-table'>
            <tr>
                <td> Expira
                    <input class='input-field'></input>
                </td>
                <td>CVC
                    <input class='input-field'></input>
                </td>
                <td>Ingrese Monto a donar
                    <input class='input-field' style="margin-left: 5px;"></input>
                </td>
            </tr>
        </table>

        <button class='pay-btn'>Verificar</button>

    </div>

</div>




{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/dist/css/credit.css' %}">
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}
{% load static %}

{% block contenido %}

<link rel="stylesheet" href="{% static 'app/dist/css/agremod.css' %}">

<div class="container">
    <section class="forma">
        <div class="row">
            <div class="col-lg-3 col-6">
                <div class="small-box bg-info">
                </div>
            </div>
            <div class="col-lg-6 col-12">
                <div>
                    <video class="responsive-video" controls="controls" muted="muted" autoplay="autoplay" width="100%">
                        <source src="{% static 'app/dist/img/PublicidadArbol.mp4' %}" type="video/mp4">
                       
                    </video>
                    
                </div>
            </div>
            <div class="col-lg-3 col-6">
                <div class="small-box bg-danger">
                </div>
            </div>
        </div>
        <!-- ./col -->
        <div class="row">
            <div class="col-lg-1 col-1">
                <div class="small-box bg-info">
                </div>
            </div>
            <div class="col-lg-10 col-12">
                <div>
                    <div class=" text-center">
                        <h1 class="display-4 mt-4">Nuestra fundacion</h1>
                        
                    </div>
                    <p>
                        En Cultiva tienes la posibilidad de aportar regalando una tarjeta con sentido, que equivale a
                        plantar un
                        árbol nativo en nombre de la persona a quien regalas, ya sea por motivo de alguna celebración,
                        un
                        nacimiento o fallecimiento o en forma de agradecimiento.Cada donación contempla los materiales e
                        insumos
                        requeridos para la plantación del árbol, por medio de una reforestación participativa organizada
                        por
                        Cultiva junto a la comunidad, además de la implementación de un sistema de riego y la mantención
                        por
                        2
                        temporadas secas (Octubre-Mayo).

                    </p>
                    <p>
                        El aporte por cada tarjeta o árbol es de $8.000; al realizar la donación podrás seleccionar si
                        quieres
                        que llegue al destinatario en forma digital o física. En este último caso se agregará $2.500
                        correspondientes al costo de materiales, impresión y envío a través de correo certificado. El
                        tiempo
                        aproximado de despacho es 5 días hábiles dentro de la Región Metropolitana.En la tarjeta se
                        puede
                        agregar un mensaje de hasta 130 caracteres (incluyendo espacios).
                    </p>
                    <p>
                        AVISO: Si seleccionas la opción WEBPAY la tarjeta se emitirá de inmediato; si escoges la opción
                        TRANSFERENCIA BANCARIA la emisión de la tarjeta quedará pendiente hasta cuando nosotros no
                        validemos
                        el
                        ingreso de la transferencia.
                    </p>
                    <div class=" text-center" style="padding: 15px;">
                        <input type="submit" value="Registrarse" class="btn btn-success " style="width: 50%; ">
                    </div>
                </div>
            </div>
            <div class="col-lg-1 col-1">
                <div class="small-box bg-danger">
                </div>
            </div>
        </div>

        <div class="card-deck mb-3 text-center">

            <div class="card mb-4 shadow-sm">
                <div class="card-header"><img src="{% static 'app/dist/img/plantando1.jpeg' %}" height="217px"
                        class="card-img-top"></div>
            </div>
            <div class="card mb-4 shadow-sm">
                <div class="card-header">
                    <img src="{% static 'app/dist/img/plantando2.jpg' %}" height="217px" class="card-img-top">
                </div>
            </div>

            <div class="card mb-4 shadow-sm">
                <div class="card-header">
                    <img src="{% static 'app/dist/img/plantando3.jpg' %}" height="217px" class="card-img-top">
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

app/templates/app/modificar.html
{% extends 'app/base.html' %}
{% load static %}
{% block contenido %}
<table class="table table-condensed">
    <thead>
        <tr>
            <td>IMAGEN</td>
            <td>NOMBRE</td>
            <td>PRECIO</td>
            <td>STOCK</td>
            <td>DESCRIPCION</td>
            <td>CATEGORIA</td>
            <td>FECHA</td>
        </tr>
    </thead>
    <tbody>
        {% for aux in listasProductos %}
        <tr>
            <td>
                {% if aux.imagen %}

                <img src="{{ aux.imagen.url }}" alt="" width="50" height="50">

                {% else %}

                <p> No posee imagen.</p>

                {% endif %}
            </td>
            <td>{{ aux.nombre }}</td>
            <td>{{ aux.precio }}</td>
            <td>{{ aux.stock }}</td>
            <td>{{ aux.descripcion }}</td>
            <td>{{ aux.categoria }}</td>
            <td>{{ aux.fecha }}</td>
            <td>
                {% if perms.app.change_producto %}
                <a href="{% url 'modificar_producto' aux.id %}" class="btn btn-info">Modificar</a>
                <a onclick="confirmarDelete({{ aux.id }})" class="btn btn-danger">Elimar</a>
                {% endif %}

            </td>


        </tr>
        {% endfor %}
    </tbody>
</table>

<div>
    {% include 'app/paginator.html' %}
</div>
{% endblock %}

{% block javascript %}
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'app/dist/js/funcionalidades.js' %}"></script>
{% endblock %}

app/templates/app/modificar_producto.html
{% extends 'app/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block contenido %}
{% block javascript %}
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="{% static 'app/dist/js/funcionalidades.js' %}"></script>
{% endblock %}
<link rel="stylesheet" href="{% static 'app/dist/css/agremod.css' %}">

<section class="forma">
    <div class="row">
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{form|crispy}}
                </table>
                {% if perms.app.change_producto %}
                <input type="submit" class="btn btn-success" value="Guardar">
                {% endif %}

            </form>
            {{mensaje}}
        </div>
        <div class="col-sm-2"></div>
    </div>
</section>

{% endblock %}

app/templates/app/pago.html
{% extends 'app/base.html' %}
{% load static %}


{% block contenido %}
<div class='container'>
  <div class='window'>
    <div class='order-info'>
      <div class='order-info-content'>
        <h2>Resumen de la orden</h2>
        <table class='order-table'>
        </table>
        <table class='order-table'>
        </table>
        <table class='order-table'>
        </table>
        <div class='line'></div>
        <div class='total'>
          <span style='float:left;'>
            <div class='thin dense'>IVA 19%</div>
            <div class='thin dense'>Envio</div>
            <div class='thin dense'>Codigo Descuento</div>
            <div class='thin dense'>TOTAL</div>
          </span>
          <span style='float:right; text-align:right;'>
          </span>
        </div>
      </div>

    </div>
  </div>
</div>



{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app/dist/css/credit.css' %}">
{% endblock %}